### PR TITLE
Support for PHP 7.2

### PR DESCRIPTION
**Pull request by szemek**
I updated all packages to use PHP 7.2. mcrypt is no longer available for this PHP version.
https://www.php.net/manual/en/intro.mcrypt.php

### CODE REVIEW

**Comment by akondas** [comment]
Thanks, maybe you can fix link `https://galaxy.ansible.com/itcraftsmanpl/php7/` -> `https://galaxy.ansible.com/akondas/php7/` as well?

**Comment by akondas** [comment]
And also link in example:
```
- hosts: webservers
  roles:
    - { role: itcraftsmanpl.php7 }
```

to

```
- hosts: webservers
  roles:
    - { role: akondas.php7 }
```

**Review by akondas — COMMENTED** [review]
Looks great :+1:

**Comment by szemek** [comment]
@akondas I added changes you mentioned to this PR.

By the way, do you experience similar errors when using ansible-galaxy?

```bash
$ ansible-galaxy install akondas.php7

- downloading role 'php7', owned by akondas
 [WARNING]: - akondas.php7 was NOT installed successfully: - sorry, akondas.php7 was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by akondas** [comment]
Sorry for problems, we must stick with `itcraftsmanpl`, Galaxy doesn't allow to change namespace: https://github.com/ansible/galaxy-issues/issues/66

**Comment by szemek** [comment]
@akondas thanks for the explanation for this error.
Nevertheless link still needs to be updated because https://galaxy.ansible.com/itcraftsmanpl/php7/ redirects to https://galaxy.ansible.com/not-found

You might want to check **Installation** line https://galaxy.ansible.com/akondas/php7
image

Do you want me to introduce any other changes in this PR?

**Comment by akondas** [comment]
Eh, looks like we must wiat for manual change: https://github.com/ansible/galaxy/issues/2059

**Comment by akondas** [comment]
In mean time you can change it back to `akondas`. Sorry for the confusion and thanks for patience.

**Comment by szemek** [comment]
@akondas roger that. I updated README again. Please mention me back in this thread after successful reimport of your namespace.

**Comment by szemek** [comment]
@akondas https://github.com/ansible/galaxy/issues/2059#issuecomment-541075185

**Comment by szemek** [comment]
@akondas can you check if that instruction works for you
https://galaxy.ansible.com/docs/contributing/importing.html#getting-started ?
It would be nice to have my changes merged 😉

**Comment by akondas** [comment]
Unfortunately, I still have a blank card:
Screenshot from 2020-03-20 06-46-24

**Pull request closed without merging**
